# Generated by Django 3.0.7 on 2023-05-05 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, unique=True, verbose_name='类别名')),
                ('description', models.TextField(blank=True, help_text='类别描述', null=True, verbose_name='类别描述')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热门')),
            ],
            options={
                'verbose_name': '作品类型',
                'verbose_name_plural': '作品类型',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(upload_to='productImage/%Y%m%d')),
            ],
            options={
                'db_table': 'productImage',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='作品名称')),
                ('product_type', models.CharField(choices=[('0', 'sale'), ('1', 'rent')], default='sale', max_length=30, verbose_name='作品类型')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='作品详情')),
                ('delete_flag', models.BooleanField(default=False)),
                ('browsing_volume', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('collecit_volume', models.IntegerField(default=0, verbose_name='collect_time')),
                ('add_like', models.IntegerField(default=0, verbose_name='add_like time')),
                ('owner_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='作品所有者位置')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='Product.Category', verbose_name='作品类别')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myproduct', to='Login.Userinfo')),
                ('product_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProductImage', to='Product.ProductImage')),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品',
            },
        ),
    ]
