# Generated by Django 3.0.7 on 2023-05-05 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(upload_to='avatar/%Y%m%d')),
            ],
            options={
                'db_table': 'avatar',
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='用户姓名')),
                ('nickname', models.CharField(blank=True, max_length=16, null=True, verbose_name='用户微信名')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生年月')),
                ('gender', models.CharField(blank=True, choices=[('1', '男'), ('0', '女')], default='1', max_length=6, null=True, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('school_number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='学号')),
                ('human_height', models.IntegerField(blank=True, null=True, verbose_name='身高')),
                ('school', models.CharField(blank=True, default='上海财经大学', max_length=60, null=True, verbose_name='学校')),
                ('home', models.CharField(blank=True, max_length=50, null=True, verbose_name='家乡')),
                ('profession', models.CharField(blank=True, max_length=60, null=True, verbose_name='专业')),
                ('location_house', models.CharField(blank=True, max_length=100, null=True, verbose_name='宿舍楼')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='电话')),
                ('unionId', models.CharField(blank=True, max_length=50, null=True, verbose_name='unionId')),
                ('open_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='openid')),
                ('session_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='session_key')),
                ('info', models.CharField(blank=True, max_length=50, null=True, verbose_name='个人简介')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('collect_time', models.IntegerField(default=0)),
                ('is_showinfo', models.BooleanField(default=True, verbose_name='是否显示资料')),
                ('wx_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='微信位置')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_avatar', to='Login.Avatar')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
