# Generated by Django 3.0.7 on 2023-05-05 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='Avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_avatar', to='Login.Avatar'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='图片'),
        ),
    ]
